/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/wsfs/workspaces/{workspace_id}/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize */
        post: operations["initialize_wsfs_workspaces__workspace_id__initialize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transact */
        post: operations["transact_wsfs_workspaces__workspace_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/blobs/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Blob
         * @description Served only to a workspace that WRITES these bytes somewhere.
         *
         *     A hash is not a secret: it travels in `X-Content-Hash`, in every
         *     `BinaryBody`, and through any client that ever held the file. So
         *     knowing one buys nothing here -- the caller has to be someone the host
         *     lets into a workspace whose own content log names it.
         */
        get: operations["fetch_blob_wsfs_workspaces__workspace_id__blobs__digest__get"];
        /**
         * Store
         * @description Under a workspace because that is the only question a host's
         *     `authorize` can answer. The bytes themselves are stored once for the
         *     deployment and named by their hash -- two workspaces holding the same
         *     file hold one copy -- but somebody who may reach no workspace at all
         *     may not fill the deployment's disk either.
         */
        put: operations["store_wsfs_workspaces__workspace_id__blobs__digest__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/entries/{entry_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Content
         * @description Omitting `content` asks for the entry's newest.
         */
        get: operations["content_wsfs_workspaces__workspace_id__entries__entry_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description The token is the credential here -- EventSource cannot carry a
         *     header, which is why it is single-use and position-bound.
         */
        get: operations["events_wsfs_workspaces__workspace_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BinaryBody */
        BinaryBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Hash */
            hash: string;
            /** Size */
            size: number;
            /** Mime */
            mime: string;
        };
        /** Create */
        Create: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "create";
            type: components["schemas"]["Type"];
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
            /** Content */
            content: (components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"]) | null;
        };
        /** Delete */
        Delete: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "delete";
            seen: components["schemas"]["Seen"];
        };
        /**
         * Event
         * @enum {string}
         */
        Event: "create" | "name" | "parent" | "move" | "delete" | "write";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitializeRequest */
        InitializeRequest: {
            /** Outbox */
            outbox?: (components["schemas"]["Create"] | components["schemas"]["Delete"] | components["schemas"]["Rename"] | components["schemas"]["Reparent"] | components["schemas"]["Move"] | components["schemas"]["Write"])[];
        };
        /**
         * InitializeResponse
         * @description DEPARTURE: `applied` is transaction ids. The contract echoes back the
         *     full requests, which the client already holds and evicts by id.
         */
        InitializeResponse: {
            /** Token */
            token: string;
            /** Entries */
            entries: components["schemas"]["Metadata"][];
            /** Applied */
            applied: string[];
            /** Rejected */
            rejected: components["schemas"]["Rejection"][];
        };
        /**
         * Metadata
         * @description Pure namespace, plus the four tokens the next mutation must present.
         *
         *     No content descriptor ever appears here: `content_version` names the write
         *     to fetch, not what it holds.
         */
        Metadata: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["Type"];
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
            /** Deleted */
            deleted?: boolean | null;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version?: string | null;
        };
        /**
         * Move
         * @description A rename and a reparent as one transaction.
         *
         *     A filesystem `mv` changes where an entry lives and what it is called at
         *     once, and doing that as two transactions can half-succeed: the rename
         *     lands, the reparent is refused, and the entry ends up somewhere nobody
         *     asked for. This presents both tokens and takes both positions or neither.
         */
        Move: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move";
            /** Name */
            name: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /** Parent */
            parent?: string | null;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
        };
        /**
         * Moved
         * @description Where an entry went, and what it is called now.
         */
        Moved: {
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
        };
        /** Rejection */
        Rejection: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /** Reason */
            reason: string;
            /** Version */
            version?: string | null;
        };
        /** Rename */
        Rename: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "rename";
            /** Name */
            name: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
        };
        /** Reparent */
        Reparent: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reparent";
            /** Parent */
            parent?: string | null;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
        };
        /**
         * Seen
         * @description Every token of the entry a delete was looking at.
         *
         *     Delete is the destructive operation, and the question worth asking is not
         *     "has the deleted flag moved" -- it almost never has -- but "is this still
         *     the thing I was told to destroy".
         */
        Seen: {
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version: string | null;
        };
        /**
         * StreamEvent
         * @description DEPARTURE: a create's metadata rides in `value`, as every other event's
         *     payload does. The contract spreads it over the event, where its `type`
         *     ("file"/"folder") is shadowed by the event's own `type` ("create") and the
         *     client can no longer tell a file from a folder.
         *
         *     `transaction` does the job the old `version` field did as well: it is the
         *     id of the transaction this event announces, which IS the new token for the
         *     property it changed. On an event for property P, set the value and set P's
         *     token to `transaction`.
         */
        StreamEvent: {
            type: components["schemas"]["Event"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /** Value */
            value?: components["schemas"]["Metadata"] | components["schemas"]["Moved"] | string | boolean | null;
            /** User */
            user?: string | null;
        };
        /** TextBody */
        TextBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Content */
            content: string;
        };
        /**
         * Type
         * @enum {string}
         */
        Type: "file" | "folder";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Write */
        Write: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "write";
            /**
             * Content Version
             * Format: uuid
             */
            content_version: string;
            /** Content */
            content: components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    initialize_wsfs_workspaces__workspace_id__initialize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitializeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitializeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transact_wsfs_workspaces__workspace_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"] | components["schemas"]["Delete"] | components["schemas"]["Rename"] | components["schemas"]["Reparent"] | components["schemas"]["Move"] | components["schemas"]["Write"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_blob_wsfs_workspaces__workspace_id__blobs__digest__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_wsfs_workspaces__workspace_id__blobs__digest__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_wsfs_workspaces__workspace_id__entries__entry_id__content_get: {
        parameters: {
            query?: {
                content?: string | null;
            };
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_wsfs_workspaces__workspace_id__stream_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One `data:` line per event, in position order, and a `: hb` comment every heartbeat. Declared here because this payload is what a client's confirmed map is mutated by -- an undeclared one could not be generated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                    "application/json": components["schemas"]["StreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
