/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/wsfs/workspaces/{workspace_id}/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize */
        post: operations["initialize_wsfs_workspaces__workspace_id__initialize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transact */
        post: operations["transact_wsfs_workspaces__workspace_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Files
         * @description Add these files, at these paths, with this text.
         *
         *     THE ADDITIVE HALF of `place`, and the only half with a URL. A client
         *     logged in on behalf of a user putting files into that user's workspace
         *     is an ordinary thing to mean, and having to walk the tree, mint an id
         *     per folder and chain CAS tokens by hand to say it is a tax on saying
         *     something harmless. What it may NOT mean is the rest of `place`:
         *     `overwrite=False` is passed here and not read from the body, and
         *     `prune` has no field at all -- so nothing arriving over this route can
         *     change text it did not write or delete anything whatsoever.
         *
         *     A path already holding something else is refused, per path, rather
         *     than written over, and everything that had nowhere to conflict still
         *     lands. That is the same shape every other refusal in this package has
         *     and the reason this answers 200 with a list rather than 409 with
         *     nothing: one occupied path is a fact about the workspace, not a
         *     malformed call.
         *
         *     REPEATABLE, like the function behind it. A path already holding
         *     exactly this text is `unchanged` -- no transaction, no event, no
         *     flicker for anybody with the file open -- so a client that cannot tell
         *     whether its last attempt landed can simply send it again.
         *
         *     400, and only 400, for `place.Unusable`: a path that is not a path,
         *     one path spelled two ways, or one path asked to be both a file and the
         *     folder above another. That is the CALL being wrong, it is caught
         *     before anything is written, and a workspace half-described by it would
         *     be a state nobody asked for.
         */
        post: operations["add_files_wsfs_workspaces__workspace_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/blobs/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Blob
         * @description Served only to a workspace that WRITES these bytes somewhere.
         *
         *     A hash is not a secret: it travels in `X-Content-Hash`, in every
         *     `BinaryBody`, and through any client that ever held the file. So
         *     knowing one buys nothing here -- the caller has to be someone the host
         *     lets into a workspace whose own content log names it.
         */
        get: operations["fetch_blob_wsfs_workspaces__workspace_id__blobs__digest__get"];
        /**
         * Store
         * @description Under a workspace because that is the only question a host's
         *     `authorize` can answer -- which is also why the id appears in the path
         *     and not in this signature: the host's dependency is what reads it. The
         *     bytes themselves are stored once for the deployment and named by their
         *     hash -- two workspaces holding the same file hold one copy -- but
         *     somebody who may reach no workspace at all may not fill the
         *     deployment's disk either.
         */
        put: operations["store_wsfs_workspaces__workspace_id__blobs__digest__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/entries/{entry_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Content
         * @description Omitting `content` asks for the entry's newest.
         */
        get: operations["content_wsfs_workspaces__workspace_id__entries__entry_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/entries/{entry_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description What this file has said, newest first.
         *
         *     Scoped to the CALLER for everything except what the workspace
         *     accepted: a draft is work that reached nobody, so the author is the
         *     only person who has ever seen it, and listing somebody else's would
         *     publish typing they never shared.
         *
         *     Paged by `before` rather than by an offset, because rows arrive while
         *     somebody is reading and an offset would show one twice or skip one.
         */
        get: operations["history_wsfs_workspaces__workspace_id__entries__entry_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/entries/{entry_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Executions
         * @description What running this file has produced, newest first.
         */
        get: operations["executions_wsfs_workspaces__workspace_id__entries__entry_id__executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot Taken
         * @description Which entries a snapshot named, and at which versions.
         */
        get: operations["snapshot_taken_wsfs_workspaces__workspace_id__snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stranded Drafts
         * @description Work that is still only where it was typed.
         *
         *     Uncleared drafts, which is the one question a client cannot answer for
         *     itself: the case worth reporting is the machine that never came back,
         *     and its own record of what it was holding went with it.
         */
        get: operations["stranded_drafts_wsfs_workspaces__workspace_id__drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/drafts/cleared": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Drafts
         * @description These drafts' work has since reached everybody else.
         *
         *     Cleared, not deleted. The row is still what that client had, and a
         *     snapshot may still name it.
         */
        post: operations["clear_drafts_wsfs_workspaces__workspace_id__drafts_cleared_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/reconstruction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconstruction
         * @description What a client was looking at, from the transactions it wrote down.
         *
         *     A POST because the question is a list, and a long one -- a snapshot of
         *     a whole workspace names four tokens per entry. Nothing is mutated.
         *
         *     The work is `reconstruct.reconstructed`, which anything inside this
         *     process can call directly. An assistant assembling the files a user
         *     could see when they asked a question wants the same answer this
         *     returns, and should not have to make an HTTP request to itself for it.
         */
        post: operations["reconstruction_wsfs_workspaces__workspace_id__reconstruction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description The token is the credential here -- EventSource cannot carry a
         *     header, which is why it is single-use and position-bound.
         */
        get: operations["events_wsfs_workspaces__workspace_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Conversation
         * @description This person's conversation here, newest first.
         *
         *     Scoped to the caller as well as the workspace: a workspace can have
         *     more than one person in it, and what somebody asked a tutor is theirs.
         */
        get: operations["conversation_wsfs_workspaces__workspace_id__chat_get"];
        put?: never;
        /**
         * Ask
         * @description Put a question to the tutor, and say where to hear the answer.
         *
         *     TWO CALLS, NOT ONE. Answering takes seconds and a request should not,
         *     so this records the question, starts the work and returns -- and the
         *     stream below attaches to work that is already under way. A client that
         *     never attaches changes nothing: the answer is written down when it
         *     finishes, because a person who asks and closes the tab has still
         *     asked.
         *
         *     ASKING TWICE IS ANSWERED ONCE. The message id is the client's, so a
         *     retried request finds its own question already here. It still gets a
         *     token, because the reason to retry is usually that the first answer
         *     never arrived.
         */
        post: operations["ask_wsfs_workspaces__workspace_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hear
         * @description The answer, as it is written.
         *
         *     The token names a generation running in this process rather than a
         *     durable fact, so it is not spent by being read: a page that reloaded
         *     mid-answer picks the same one up again. What retires it is the answer
         *     being old, not somebody having heard it.
         */
        get: operations["hear_wsfs_workspaces__workspace_id__chat_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Progress
         * @description Whether a student has got anywhere since a few minutes ago.
         *
         *     NOT A QUESTION, and not part of anybody's conversation: no transcript
         *     goes in and no turn comes out. It is one measurement, asked on a timer
         *     by the client that is watching somebody work -- which is why it does
         *     not stream, does not take a message id, and is not recorded. What is
         *     recorded is the episode, and only if the answer is no.
         *
         *     Answered synchronously because the caller has nobody waiting on it.
         */
        post: operations["progress_wsfs_workspaces__workspace_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/study/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stuck Episode
         * @description A student was detected as stuck, and what the protocol did about it.
         */
        post: operations["stuck_episode_wsfs_workspaces__workspace_id__study_episodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/study/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stuck Offer
         * @description A student took a prompt that was offered to them.
         */
        post: operations["stuck_offer_wsfs_workspaces__workspace_id__study_offers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/study/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stuck Activity
         * @description A batch of what a student did inside a post-episode window.
         */
        post: operations["stuck_activity_wsfs_workspaces__workspace_id__study_activity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure Room
         * @description Make this entry's room exist and say what the file says.
         *
         *     Idempotent, and the only way a room is ever filled. Free when there is
         *     nothing to do, which is the common case by a wide margin: the common
         *     reason to ask is that somebody just saved and every other client with
         *     the file open heard about it.
         *
         *     A null base is not a failure. It is what a file that is not text a
         *     room can hold answers -- bytes written over it, or a deletion -- and
         *     the caller's own read is the first moment anybody could know that.
         */
        post: operations["ensure_room_wsfs_workspaces__workspace_id__rooms__entry_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}/warm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Warm Room
         * @description Fill this room now, so that opening the file later is instant.
         *
         *     Creating a room, asking what it holds and filling it is three calls to
         *     the collaboration server and takes a second or two. Somebody opening a
         *     file waits for all of it, because an editor bound to a room that has
         *     not been filled shows an empty document and then saves that over the
         *     real file.
         *
         *     Nobody is waiting when a file is CREATED, so that is where this
         *     belongs -- whether a person made it or a workspace was cloned for one.
         *     Answered before the work starts, because the answer is not the point.
         */
        post: operations["warm_room_wsfs_workspaces__workspace_id__rooms__entry_id__warm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}/stored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Room Stored
         * @description A member of this room wrote the file.
         *
         *     The cheap half of the whole design: this host is told where the file
         *     now stands instead of every client that hears about the write asking
         *     the collaboration server what the room contains. One POST here, and
         *     everybody else's settle finds nothing to do.
         */
        post: operations["room_stored_wsfs_workspaces__workspace_id__rooms__entry_id__stored_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand Over
         * @description Put a client's own document update into the room for it.
         *
         *     The one thing a client cannot do for itself when it can reach this
         *     host and not the collaboration server. Its work is already kept as a
         *     draft and cannot be lost -- but nobody else would see it until that
         *     connection came back, which can be a long time and is not a good
         *     enough reason.
         *
         *     FORWARDED, NOT INTERPRETED. The update carries its own identities, so
         *     it merges exactly once however many routes it arrives by, including
         *     this client's own connection when that returns.
         *
         *     Sized like a blob, and for the same reason: this is the one route here
         *     whose body a caller chooses the length of.
         */
        post: operations["hand_over_wsfs_workspaces__workspace_id__rooms__entry_id__updates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Accepted
         * @description A student took the offer.
         */
        Accepted: {
            /**
             * Offer
             * Format: uuid
             */
            offer: string;
            /**
             * Episode
             * Format: uuid
             */
            episode: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Offset */
            offset?: number | null;
            /** Course Event */
            course_event?: string | null;
            /** Entry */
            entry?: string | null;
        };
        /**
         * Answering
         * @description One line of the answer stream.
         *
         *     TWO KINDS, and the second is not a courtesy. A delta is a piece; `ended`
         *     carries the whole text and whatever went wrong, so a client that joined
         *     late, missed a frame, or wants to check what it assembled has the answer
         *     itself rather than only the pieces of it.
         */
        Answering: {
            /**
             * Type
             * @enum {string}
             */
            type: "delta" | "ended";
            /**
             * Delta
             * @default
             */
            delta: string;
            /**
             * Text
             * @default
             */
            text: string;
            /** Failure */
            failure?: string | null;
        };
        /**
         * Asked
         * @description Where to listen for the answer.
         *
         *     The message id comes back too, though the client minted it: a client that
         *     asked twice is told which question this is the answer to, rather than
         *     having to assume.
         */
        Asked: {
            /**
             * Message
             * Format: uuid
             */
            message: string;
            /** Token */
            token: string;
        };
        /**
         * Asking
         * @description A question, and everything needed to answer it in context.
         */
        Asking: {
            /**
             * Message
             * Format: uuid
             */
            message: string;
            /** Text */
            text: string;
            /** Snapshot */
            snapshot?: string | null;
            /** Attached */
            attached?: components["schemas"]["Attaching"][];
            /** Offset */
            offset?: number | null;
            /** System */
            system?: string | null;
        };
        /** Attached */
        Attached: {
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            /** Executions */
            executions?: components["schemas"]["Executed"][];
        };
        /**
         * Attaching
         * @description One file put in front of the tutor, and which of its runs came too.
         */
        Attaching: {
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            /** Executions */
            executions?: string[];
        };
        /**
         * Became
         * @description What the protocol did with one detection.
         *
         *     FOUR VALUES, NOT TWO. `offered` and `silent` are the randomized arms and
         *     the ones an analysis compares; the other two are detections that were
         *     never eligible, because a cooldown or a post-episode window was running.
         *     Recording them is what makes "this student was stuck four times and heard
         *     about it once" different from "this student was stuck once".
         * @enum {string}
         */
        Became: "offered" | "silent" | "held back by the cooldown" | "held back by a post-episode window";
        /** BinaryBody */
        BinaryBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Hash */
            hash: string;
            /** Size */
            size: number;
            /** Mime */
            mime: string;
        };
        /**
         * Change
         * @description What one path needed doing to it.
         *
         *     UNCHANGED is the one worth having a word for. It is not a failure and not
         *     a no-op the caller should ignore -- it is this function's whole claim to
         *     being safe to run repeatedly, and a caller watching for churn wants to see
         *     that the second run was all of these.
         * @enum {string}
         */
        Change: "created" | "written" | "unchanged" | "deleted";
        /**
         * Clearing
         * @description Drafts whose work has since reached everybody else.
         */
        Clearing: {
            /** Transactions */
            transactions: string[];
        };
        /** Create */
        Create: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "create";
            type: components["schemas"]["Type"];
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
            /** Content */
            content: (components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"]) | null;
        };
        /** Delete */
        Delete: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "delete";
            seen: components["schemas"]["Seen"];
        };
        /**
         * Detected
         * @description One stuck episode, and the periods it opened.
         *
         *     ONE POST, UP TO THREE ROWS. The cooldown and the window are separate facts
         *     with separate lives -- they are read back on their own and they belong to
         *     different questions -- but they are not separate EVENTS: both are decided
         *     in the same instant as the episode, by the same coin. Sending them apart
         *     would mean a client that managed one request and not the next left an
         *     episode claiming a window that no row records.
         */
        Detected: {
            /**
             * Episode
             * Format: uuid
             */
            episode: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Offset */
            offset?: number | null;
            rule: components["schemas"]["Rule"];
            became: components["schemas"]["Became"];
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Course Event */
            course_event?: string | null;
            /** Entry */
            entry?: string | null;
            /** Path */
            path?: string | null;
            /** Code */
            code?: string | null;
            cooldown?: components["schemas"]["Span"] | null;
            window?: components["schemas"]["Span"] | null;
        };
        /**
         * Event
         * @enum {string}
         */
        Event: "create" | "name" | "parent" | "move" | "delete" | "write";
        /**
         * Execute
         * @description One run of one file, against a snapshot, and what came out.
         *
         *     Refused when the snapshot is unknown, because output whose subject cannot
         *     be named is not evidence of anything.
         */
        Execute: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "execute";
            /**
             * Snapshot
             * Format: uuid
             */
            snapshot: string;
            /** Outputs */
            outputs?: unknown[];
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /**
         * Executed
         * @description One recorded run, as it is read back.
         */
        Executed: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Snapshot
             * Format: uuid
             */
            snapshot: string;
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            at: components["schemas"]["Occurrence"];
            /** Outputs */
            outputs: unknown[];
            /** Ok */
            ok: boolean;
        };
        /** Executions */
        Executions: {
            /** Executions */
            executions: components["schemas"]["Executed"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** History */
        History: {
            /** Versions */
            versions: components["schemas"]["Version"][];
            /** More */
            more: boolean;
        };
        /** InitializeRequest */
        InitializeRequest: {
            /** Outbox */
            outbox?: (components["schemas"]["Create"] | components["schemas"]["Delete"] | components["schemas"]["Rename"] | components["schemas"]["Reparent"] | components["schemas"]["Move"] | components["schemas"]["Write"] | components["schemas"]["Snapshot"] | components["schemas"]["Execute"])[];
        };
        /**
         * InitializeResponse
         * @description DEPARTURE: `applied` is transaction ids. The contract echoes back the
         *     full requests, which the client already holds and evicts by id.
         */
        InitializeResponse: {
            /** Token */
            token: string;
            /** Entries */
            entries: components["schemas"]["Metadata"][];
            /** Applied */
            applied: string[];
            /** Rejected */
            rejected: components["schemas"]["Rejection"][];
        };
        /** Judged */
        Judged: {
            /** Progressing */
            progressing: boolean;
            /**
             * Why
             * @default
             */
            why: string;
        };
        /**
         * Judging
         * @description Two versions of one program, and what it was meant to do.
         */
        Judging: {
            /** Goal */
            goal: string;
            /**
             * Before
             * @default
             */
            before: string;
            /**
             * After
             * @default
             */
            after: string;
        };
        /**
         * Kind
         * @enum {string}
         */
        Kind: "text" | "binary";
        /**
         * Metadata
         * @description Pure namespace, plus the four tokens the next mutation must present.
         *
         *     No content descriptor ever appears here: `content_version` names the write
         *     to fetch, not what it holds.
         */
        Metadata: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["Type"];
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
            /** Deleted */
            deleted?: boolean | null;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version?: string | null;
            modified: components["schemas"]["Occurrence"];
        };
        /**
         * Moment
         * @description One thing a student did inside a post-episode window.
         *
         *     DELIBERATELY OPEN. The shape belongs to whatever produced it -- an editor
         *     edit, a panel becoming visible, a keystroke in the chat box -- and a server
         *     that parsed them would have to be redeployed every time the client learned
         *     to notice one more thing. The same argument as `ExecutionRow.outputs`.
         *
         *     Two fields are not open, because the whole point of the window is when
         *     things happened relative to each other: `at`, and what kind of thing it
         *     was.
         */
        Moment: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Kind */
            kind: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Move
         * @description A rename and a reparent as one transaction.
         *
         *     A filesystem `mv` changes where an entry lives and what it is called at
         *     once, and doing that as two transactions can half-succeed: the rename
         *     lands, the reparent is refused, and the entry ends up somewhere nobody
         *     asked for. This presents both tokens and takes both positions or neither.
         */
        Move: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move";
            /** Name */
            name: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /** Parent */
            parent?: string | null;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
        };
        /**
         * Moved
         * @description Where an entry went, and what it is called now.
         */
        Moved: {
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
        };
        /** NotPlaced */
        NotPlaced: {
            /** Path */
            path: string;
            /** Reason */
            reason: string;
        };
        /**
         * Occurrence
         * @description When one transaction happened, in both clocks that saw it.
         *
         *     Two clocks because they answer different questions and disagree for honest
         *     reasons. `minted` is the client's, and it is when the USER acted -- which,
         *     after a week offline, is the only one that means anything to them. `accepted`
         *     is this server's, and it is when the change entered the workspace and became
         *     something other clients could see. An offline session makes the gap between
         *     them days wide, and neither number is the other's approximation.
         */
        Occurrence: {
            /** Minted */
            minted?: string | null;
            /** Offset */
            offset?: number | null;
            /** Accepted */
            accepted: string | null;
        };
        /** Placed */
        Placed: {
            /**
             * Workspace
             * Format: uuid
             */
            workspace: string;
            /** Entries */
            entries?: components["schemas"]["PlacedEntry"][];
            /** Refused */
            refused?: components["schemas"]["NotPlaced"][];
        };
        /** PlacedEntry */
        PlacedEntry: {
            /** Path */
            path: string;
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            type: components["schemas"]["Type"];
            change: components["schemas"]["Change"];
        };
        /**
         * PlacementRequest
         * @description Paths, and the text each should hold.
         *
         *     NO `prune`, and no way to ask for one. Deleting everything a body did not
         *     name is a thing a host may mean and a client may not, so it stays where
         *     the host is -- an argument to the in-process `Mounted.place`, never a
         *     field on the wire. See `PlaceFiles`.
         */
        PlacementRequest: {
            /** Files */
            files?: {
                [key: string]: string;
            };
        };
        /**
         * Reconstructed
         * @description What those transactions said -- whichever way each of them went.
         *
         *     Nothing here says whether a transaction was accepted. That is deliberate:
         *     the question this answers is what the USER WAS SEEING, and a client shows
         *     its own queued work before the server has ruled on it. A transaction later
         *     refused still described the screen at the moment it was taken.
         */
        Reconstructed: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
            /** Parent */
            parent?: string | null;
            /** Deleted */
            deleted?: boolean | null;
            /** Content */
            content?: (components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"]) | null;
            /**
             * Unresolved
             * @default []
             */
            unresolved: string[];
        };
        /** ReconstructionRequest */
        ReconstructionRequest: {
            /** Entries */
            entries: components["schemas"]["Versions"][];
        };
        /** ReconstructionResponse */
        ReconstructionResponse: {
            /** Entries */
            entries: components["schemas"]["Reconstructed"][];
        };
        /**
         * Recorded
         * @description A batch of moments, flushed from one open window.
         *
         *     A BATCH RATHER THAN AN EVENT, because a keystroke is not worth a request.
         *     Each moment carries its own timestamp, so when it was recorded stays a
         *     fact about the student even though when it arrived is a fact about the
         *     network.
         */
        Recorded: {
            /**
             * Episode
             * Format: uuid
             */
            episode: string;
            /** Moments */
            moments?: components["schemas"]["Moment"][];
        };
        /** Rejection */
        Rejection: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /** Reason */
            reason: string;
            /** Version */
            version?: string | null;
        };
        /** Rename */
        Rename: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "rename";
            /** Name */
            name: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
        };
        /** Reparent */
        Reparent: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reparent";
            /** Parent */
            parent?: string | null;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
        };
        /**
         * RoomStanding
         * @description Where a room's text stands, as this host remembers it.
         */
        RoomStanding: {
            /** Base */
            base: string | null;
        };
        /**
         * RoomStored
         * @description A member of this room wrote the file.
         *
         *     Told rather than discovered: the room already holds the text, so the only
         *     thing that changed is where this host believes it stands. Knowing that is
         *     what makes every other client's settle cost nothing.
         */
        RoomStored: {
            /**
             * Version
             * Format: uuid
             */
            version: string;
        };
        /**
         * Rule
         * @description Why a student looked stuck. One of the three rules, and no others.
         * @enum {string}
         */
        Rule: "the same error twice" | "idle" | "no progress";
        /**
         * Seen
         * @description Every token of the entry a delete was looking at.
         *
         *     Delete is the destructive operation, and the question worth asking is not
         *     "has the deleted flag moved" -- it almost never has -- but "is this still
         *     the thing I was told to destroy".
         */
        Seen: {
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version: string | null;
        };
        /**
         * Seen_
         * @description One entry as a snapshot found it: the four tokens that ARE the entry.
         */
        Seen_: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version?: string | null;
        };
        /**
         * Snapshot
         * @description A claim that the workspace looked like this.
         *
         *     NOT A MUTATION. It changes nothing about any entry, so it presents no
         *     token, cannot conflict, and is not in the event stream. What it can be
         *     refused for is naming a version that was never issued -- a claim about a
         *     state that never existed is not worth keeping.
         *
         *     `id` is inherited and unused: a snapshot is about the workspace rather
         *     than about one entry. It carries the transaction's own id so that dedup,
         *     the outbox and `utc_offset` all work exactly as they do for everything
         *     else.
         */
        Snapshot: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "snapshot";
            /** Entries */
            entries: components["schemas"]["Seen_"][];
        };
        /** SnapshotEntry */
        SnapshotEntry: {
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version?: string | null;
        };
        /** SnapshotTaken */
        SnapshotTaken: {
            /**
             * Snapshot
             * Format: uuid
             */
            snapshot: string;
            /** Entries */
            entries: components["schemas"]["SnapshotEntry"][];
        };
        /**
         * Span
         * @description A stretch of time whose end was known when it began.
         *
         *     Both ends are the CLIENT's, and both are sent, because the protocol
         *     precalculates them: a cooldown is twenty minutes from the moment a prompt
         *     was shown, and the setting that says twenty could be different next term.
         *     Recomputing `until` here from today's configuration would describe the
         *     server's present rather than the student's past.
         */
        Span: {
            /**
             * Began
             * Format: date-time
             */
            began: string;
            /**
             * Ends
             * Format: date-time
             */
            ends: string;
        };
        /**
         * Standing
         * @description Where one version of a file stands.
         *
         *     Three, not two, because a draft is neither of the others: not what the
         *     workspace holds, and not the system declining -- it is a client saying it
         *     could not share this yet. Telling a user their own caution was a refusal
         *     would report it as a failure.
         * @enum {string}
         */
        Standing: "applied" | "draft" | "refused";
        /**
         * Stranded
         * @description A draft whose work is still only where it was typed.
         */
        Stranded: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * StrandedDrafts
         * @description What one client had and nobody else ever got.
         *
         *     The question drafts exist to answer. A machine that never comes back
         *     cannot report its own, which is why the flag is the server's.
         */
        StrandedDrafts: {
            /** Drafts */
            drafts: components["schemas"]["Stranded"][];
        };
        /**
         * StreamEvent
         * @description DEPARTURE: a create's metadata rides in `value`, as every other event's
         *     payload does. The contract spreads it over the event, where its `type`
         *     ("file"/"folder") is shadowed by the event's own `type` ("create") and the
         *     client can no longer tell a file from a folder.
         *
         *     `transaction` does the job the old `version` field did as well: it is the
         *     id of the transaction this event announces, which IS the new token for the
         *     property it changed. On an event for property P, set the value and set P's
         *     token to `transaction`.
         */
        StreamEvent: {
            type: components["schemas"]["Event"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /** Value */
            value?: components["schemas"]["Metadata"] | components["schemas"]["Moved"] | string | boolean | null;
            /** User */
            user?: string | null;
            at: components["schemas"]["Occurrence"];
        };
        /** TextBody */
        TextBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Content */
            content: string;
        };
        /** Transcript */
        Transcript: {
            /** Turns */
            turns: components["schemas"]["Turn"][];
            /** More */
            more: boolean;
        };
        /**
         * Turn
         * @description One exchange, as the panel reads it back.
         */
        Turn: {
            /**
             * Message
             * Format: uuid
             */
            message: string;
            at: components["schemas"]["Occurrence"];
            /** Text */
            text: string;
            /** Snapshot */
            snapshot?: string | null;
            /** Attached */
            attached?: components["schemas"]["Attached"][];
            /** Answer */
            answer?: string | null;
            /** Failure */
            failure?: string | null;
            /** Model */
            model?: string | null;
        };
        /**
         * Type
         * @enum {string}
         */
        Type: "file" | "folder";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Version
         * @description One thing this file has said, and where that stands.
         */
        Version: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            at: components["schemas"]["Occurrence"];
            standing: components["schemas"]["Standing"];
            kind: components["schemas"]["Kind"];
            /** Size */
            size?: number | null;
            /** Why */
            why?: string | null;
        };
        /**
         * Versions
         * @description One entry, at the transactions a client was looking at.
         *
         *     Every field but `id` is optional so that a caller can ask about as little
         *     as it knows. A client replicating a whole filesystem sends all four; one
         *     asking only what a file held sends `content_version` alone.
         */
        Versions: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name Version */
            name_version?: string | null;
            /** Parent Version */
            parent_version?: string | null;
            /** Deleted Version */
            deleted_version?: string | null;
            /** Content Version */
            content_version?: string | null;
        };
        /** Write */
        Write: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "write";
            /**
             * Content Version
             * Format: uuid
             */
            content_version: string;
            /** Content */
            content: components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"];
            /**
             * Draft
             * @default false
             */
            draft: boolean;
            /** Predecessor */
            predecessor?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    initialize_wsfs_workspaces__workspace_id__initialize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitializeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitializeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transact_wsfs_workspaces__workspace_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"] | components["schemas"]["Delete"] | components["schemas"]["Rename"] | components["schemas"]["Reparent"] | components["schemas"]["Move"] | components["schemas"]["Write"] | components["schemas"]["Snapshot"] | components["schemas"]["Execute"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_files_wsfs_workspaces__workspace_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlacementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Placed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_blob_wsfs_workspaces__workspace_id__blobs__digest__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_wsfs_workspaces__workspace_id__blobs__digest__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_wsfs_workspaces__workspace_id__entries__entry_id__content_get: {
        parameters: {
            query?: {
                content?: string | null;
            };
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_wsfs_workspaces__workspace_id__entries__entry_id__history_get: {
        parameters: {
            query?: {
                before?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    executions_wsfs_workspaces__workspace_id__entries__entry_id__executions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Executions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_taken_wsfs_workspaces__workspace_id__snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotTaken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stranded_drafts_wsfs_workspaces__workspace_id__drafts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrandedDrafts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_drafts_wsfs_workspaces__workspace_id__drafts_cleared_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Clearing"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconstruction_wsfs_workspaces__workspace_id__reconstruction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconstructionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconstructionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_wsfs_workspaces__workspace_id__stream_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One `data:` line per event, in position order, and a `: hb` comment every heartbeat. Declared here because this payload is what a client's confirmed map is mutated by -- an undeclared one could not be generated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                    "application/json": components["schemas"]["StreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversation_wsfs_workspaces__workspace_id__chat_get: {
        parameters: {
            query?: {
                before?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_wsfs_workspaces__workspace_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Asking"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asked"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hear_wsfs_workspaces__workspace_id__chat_stream_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One `data:` line per delta, then one saying it ended. Declared so a client can be generated against it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                    "application/json": components["schemas"]["Answering"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    progress_wsfs_workspaces__workspace_id__progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Judging"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Judged"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stuck_episode_wsfs_workspaces__workspace_id__study_episodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Detected"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stuck_offer_wsfs_workspaces__workspace_id__study_offers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Accepted"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stuck_activity_wsfs_workspaces__workspace_id__study_activity_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recorded"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_room_wsfs_workspaces__workspace_id__rooms__entry_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStanding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    warm_room_wsfs_workspaces__workspace_id__rooms__entry_id__warm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_stored_wsfs_workspaces__workspace_id__rooms__entry_id__stored_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomStored"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hand_over_wsfs_workspaces__workspace_id__rooms__entry_id__updates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
