/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/wsfs/workspaces/{workspace_id}/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize */
        post: operations["initialize_wsfs_workspaces__workspace_id__initialize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transact */
        post: operations["transact_wsfs_workspaces__workspace_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/blobs/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Blob
         * @description Served only to a workspace that WRITES these bytes somewhere.
         *
         *     A hash is not a secret: it travels in `X-Content-Hash`, in every
         *     `BinaryBody`, and through any client that ever held the file. So
         *     knowing one buys nothing here -- the caller has to be someone the host
         *     lets into a workspace whose own content log names it.
         */
        get: operations["fetch_blob_wsfs_workspaces__workspace_id__blobs__digest__get"];
        /**
         * Store
         * @description Under a workspace because that is the only question a host's
         *     `authorize` can answer -- which is also why the id appears in the path
         *     and not in this signature: the host's dependency is what reads it. The
         *     bytes themselves are stored once for the deployment and named by their
         *     hash -- two workspaces holding the same file hold one copy -- but
         *     somebody who may reach no workspace at all may not fill the
         *     deployment's disk either.
         */
        put: operations["store_wsfs_workspaces__workspace_id__blobs__digest__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/entries/{entry_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Content
         * @description Omitting `content` asks for the entry's newest.
         */
        get: operations["content_wsfs_workspaces__workspace_id__entries__entry_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/entries/{entry_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description What this file has said, newest first.
         *
         *     Scoped to the CALLER for everything except what the workspace
         *     accepted: a draft is work that reached nobody, so the author is the
         *     only person who has ever seen it, and listing somebody else's would
         *     publish typing they never shared.
         *
         *     Paged by `before` rather than by an offset, because rows arrive while
         *     somebody is reading and an offset would show one twice or skip one.
         */
        get: operations["history_wsfs_workspaces__workspace_id__entries__entry_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/entries/{entry_id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Executions
         * @description What running this file has produced, newest first.
         */
        get: operations["executions_wsfs_workspaces__workspace_id__entries__entry_id__executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshot Taken
         * @description Which entries a snapshot named, and at which versions.
         */
        get: operations["snapshot_taken_wsfs_workspaces__workspace_id__snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stranded Drafts
         * @description Work that is still only where it was typed.
         *
         *     Uncleared drafts, which is the one question a client cannot answer for
         *     itself: the case worth reporting is the machine that never came back,
         *     and its own record of what it was holding went with it.
         */
        get: operations["stranded_drafts_wsfs_workspaces__workspace_id__drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/drafts/cleared": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Drafts
         * @description These drafts' work has since reached everybody else.
         *
         *     Cleared, not deleted. The row is still what that client had, and a
         *     snapshot may still name it.
         */
        post: operations["clear_drafts_wsfs_workspaces__workspace_id__drafts_cleared_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/reconstruction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconstruction
         * @description What a client was looking at, from the transactions it wrote down.
         *
         *     A POST because the question is a list, and a long one -- a snapshot of
         *     a whole workspace names four tokens per entry. Nothing is mutated.
         *
         *     The work is `reconstruct.reconstructed`, which anything inside this
         *     process can call directly. An assistant assembling the files a user
         *     could see when they asked a question wants the same answer this
         *     returns, and should not have to make an HTTP request to itself for it.
         */
        post: operations["reconstruction_wsfs_workspaces__workspace_id__reconstruction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description The token is the credential here -- EventSource cannot carry a
         *     header, which is why it is single-use and position-bound.
         */
        get: operations["events_wsfs_workspaces__workspace_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ensure Room
         * @description Make this entry's room exist and say what the file says.
         *
         *     Idempotent, and the only way a room is ever filled. Free when there is
         *     nothing to do, which is the common case by a wide margin: the common
         *     reason to ask is that somebody just saved and every other client with
         *     the file open heard about it.
         *
         *     A null base is not a failure. It is what a file that is not text a
         *     room can hold answers -- bytes written over it, or a deletion -- and
         *     the caller's own read is the first moment anybody could know that.
         */
        post: operations["ensure_room_wsfs_workspaces__workspace_id__rooms__entry_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}/warm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Warm Room
         * @description Fill this room now, so that opening the file later is instant.
         *
         *     Creating a room, asking what it holds and filling it is three calls to
         *     the collaboration server and takes a second or two. Somebody opening a
         *     file waits for all of it, because an editor bound to a room that has
         *     not been filled shows an empty document and then saves that over the
         *     real file.
         *
         *     Nobody is waiting when a file is CREATED, so that is where this
         *     belongs -- whether a person made it or a workspace was cloned for one.
         *     Answered before the work starts, because the answer is not the point.
         */
        post: operations["warm_room_wsfs_workspaces__workspace_id__rooms__entry_id__warm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}/stored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Room Stored
         * @description A member of this room wrote the file.
         *
         *     The cheap half of the whole design: this host is told where the file
         *     now stands instead of every client that hears about the write asking
         *     the collaboration server what the room contains. One POST here, and
         *     everybody else's settle finds nothing to do.
         */
        post: operations["room_stored_wsfs_workspaces__workspace_id__rooms__entry_id__stored_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wsfs/workspaces/{workspace_id}/rooms/{entry_id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand Over
         * @description Put a client's own document update into the room for it.
         *
         *     The one thing a client cannot do for itself when it can reach this
         *     host and not the collaboration server. Its work is already kept as a
         *     draft and cannot be lost -- but nobody else would see it until that
         *     connection came back, which can be a long time and is not a good
         *     enough reason.
         *
         *     FORWARDED, NOT INTERPRETED. The update carries its own identities, so
         *     it merges exactly once however many routes it arrives by, including
         *     this client's own connection when that returns.
         *
         *     Sized like a blob, and for the same reason: this is the one route here
         *     whose body a caller chooses the length of.
         */
        post: operations["hand_over_wsfs_workspaces__workspace_id__rooms__entry_id__updates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BinaryBody */
        BinaryBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "binary";
            /** Hash */
            hash: string;
            /** Size */
            size: number;
            /** Mime */
            mime: string;
        };
        /**
         * Clearing
         * @description Drafts whose work has since reached everybody else.
         */
        Clearing: {
            /** Transactions */
            transactions: string[];
        };
        /** Create */
        Create: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "create";
            type: components["schemas"]["Type"];
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
            /** Content */
            content: (components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"]) | null;
        };
        /** Delete */
        Delete: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "delete";
            seen: components["schemas"]["Seen"];
        };
        /**
         * Event
         * @enum {string}
         */
        Event: "create" | "name" | "parent" | "move" | "delete" | "write";
        /**
         * Execute
         * @description One run of one file, against a snapshot, and what came out.
         *
         *     Refused when the snapshot is unknown, because output whose subject cannot
         *     be named is not evidence of anything.
         */
        Execute: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "execute";
            /**
             * Snapshot
             * Format: uuid
             */
            snapshot: string;
            /** Outputs */
            outputs?: unknown[];
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /**
         * Executed
         * @description One recorded run, as it is read back.
         */
        Executed: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Snapshot
             * Format: uuid
             */
            snapshot: string;
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            at: components["schemas"]["Occurrence"];
            /** Outputs */
            outputs: unknown[];
            /** Ok */
            ok: boolean;
        };
        /** Executions */
        Executions: {
            /** Executions */
            executions: components["schemas"]["Executed"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** History */
        History: {
            /** Versions */
            versions: components["schemas"]["Version"][];
            /** More */
            more: boolean;
        };
        /** InitializeRequest */
        InitializeRequest: {
            /** Outbox */
            outbox?: (components["schemas"]["Create"] | components["schemas"]["Delete"] | components["schemas"]["Rename"] | components["schemas"]["Reparent"] | components["schemas"]["Move"] | components["schemas"]["Write"] | components["schemas"]["Snapshot"] | components["schemas"]["Execute"])[];
        };
        /**
         * InitializeResponse
         * @description DEPARTURE: `applied` is transaction ids. The contract echoes back the
         *     full requests, which the client already holds and evicts by id.
         */
        InitializeResponse: {
            /** Token */
            token: string;
            /** Entries */
            entries: components["schemas"]["Metadata"][];
            /** Applied */
            applied: string[];
            /** Rejected */
            rejected: components["schemas"]["Rejection"][];
        };
        /**
         * Kind
         * @enum {string}
         */
        Kind: "text" | "binary";
        /**
         * Metadata
         * @description Pure namespace, plus the four tokens the next mutation must present.
         *
         *     No content descriptor ever appears here: `content_version` names the write
         *     to fetch, not what it holds.
         */
        Metadata: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["Type"];
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
            /** Deleted */
            deleted?: boolean | null;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version?: string | null;
            modified: components["schemas"]["Occurrence"];
        };
        /**
         * Move
         * @description A rename and a reparent as one transaction.
         *
         *     A filesystem `mv` changes where an entry lives and what it is called at
         *     once, and doing that as two transactions can half-succeed: the rename
         *     lands, the reparent is refused, and the entry ends up somewhere nobody
         *     asked for. This presents both tokens and takes both positions or neither.
         */
        Move: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "move";
            /** Name */
            name: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /** Parent */
            parent?: string | null;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
        };
        /**
         * Moved
         * @description Where an entry went, and what it is called now.
         */
        Moved: {
            /** Name */
            name: string;
            /** Parent */
            parent?: string | null;
        };
        /**
         * Occurrence
         * @description When one transaction happened, in both clocks that saw it.
         *
         *     Two clocks because they answer different questions and disagree for honest
         *     reasons. `minted` is the client's, and it is when the USER acted -- which,
         *     after a week offline, is the only one that means anything to them. `accepted`
         *     is this server's, and it is when the change entered the workspace and became
         *     something other clients could see. An offline session makes the gap between
         *     them days wide, and neither number is the other's approximation.
         */
        Occurrence: {
            /** Minted */
            minted?: string | null;
            /** Offset */
            offset?: number | null;
            /** Accepted */
            accepted: string | null;
        };
        /**
         * Reconstructed
         * @description What those transactions said -- whichever way each of them went.
         *
         *     Nothing here says whether a transaction was accepted. That is deliberate:
         *     the question this answers is what the USER WAS SEEING, and a client shows
         *     its own queued work before the server has ruled on it. A transaction later
         *     refused still described the screen at the moment it was taken.
         */
        Reconstructed: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name?: string | null;
            /** Parent */
            parent?: string | null;
            /** Deleted */
            deleted?: boolean | null;
            /** Content */
            content?: (components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"]) | null;
            /**
             * Unresolved
             * @default []
             */
            unresolved: string[];
        };
        /** ReconstructionRequest */
        ReconstructionRequest: {
            /** Entries */
            entries: components["schemas"]["Versions"][];
        };
        /** ReconstructionResponse */
        ReconstructionResponse: {
            /** Entries */
            entries: components["schemas"]["Reconstructed"][];
        };
        /** Rejection */
        Rejection: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /** Reason */
            reason: string;
            /** Version */
            version?: string | null;
        };
        /** Rename */
        Rename: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "rename";
            /** Name */
            name: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
        };
        /** Reparent */
        Reparent: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reparent";
            /** Parent */
            parent?: string | null;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
        };
        /**
         * RoomStanding
         * @description Where a room's text stands, as this host remembers it.
         */
        RoomStanding: {
            /** Base */
            base: string | null;
        };
        /**
         * RoomStored
         * @description A member of this room wrote the file.
         *
         *     Told rather than discovered: the room already holds the text, so the only
         *     thing that changed is where this host believes it stands. Knowing that is
         *     what makes every other client's settle cost nothing.
         */
        RoomStored: {
            /**
             * Version
             * Format: uuid
             */
            version: string;
        };
        /**
         * Seen
         * @description Every token of the entry a delete was looking at.
         *
         *     Delete is the destructive operation, and the question worth asking is not
         *     "has the deleted flag moved" -- it almost never has -- but "is this still
         *     the thing I was told to destroy".
         */
        Seen: {
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version: string | null;
        };
        /**
         * Seen_
         * @description One entry as a snapshot found it: the four tokens that ARE the entry.
         */
        Seen_: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version?: string | null;
        };
        /**
         * Snapshot
         * @description A claim that the workspace looked like this.
         *
         *     NOT A MUTATION. It changes nothing about any entry, so it presents no
         *     token, cannot conflict, and is not in the event stream. What it can be
         *     refused for is naming a version that was never issued -- a claim about a
         *     state that never existed is not worth keeping.
         *
         *     `id` is inherited and unused: a snapshot is about the workspace rather
         *     than about one entry. It carries the transaction's own id so that dedup,
         *     the outbox and `utc_offset` all work exactly as they do for everything
         *     else.
         */
        Snapshot: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "snapshot";
            /** Entries */
            entries: components["schemas"]["Seen_"][];
        };
        /** SnapshotEntry */
        SnapshotEntry: {
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            /**
             * Name Version
             * Format: uuid
             */
            name_version: string;
            /**
             * Parent Version
             * Format: uuid
             */
            parent_version: string;
            /**
             * Deleted Version
             * Format: uuid
             */
            deleted_version: string;
            /** Content Version */
            content_version?: string | null;
        };
        /** SnapshotTaken */
        SnapshotTaken: {
            /**
             * Snapshot
             * Format: uuid
             */
            snapshot: string;
            /** Entries */
            entries: components["schemas"]["SnapshotEntry"][];
        };
        /**
         * Standing
         * @description Where one version of a file stands.
         *
         *     Three, not two, because a draft is neither of the others: not what the
         *     workspace holds, and not the system declining -- it is a client saying it
         *     could not share this yet. Telling a user their own caution was a refusal
         *     would report it as a failure.
         * @enum {string}
         */
        Standing: "applied" | "draft" | "refused";
        /**
         * Stranded
         * @description A draft whose work is still only where it was typed.
         */
        Stranded: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Entry
             * Format: uuid
             */
            entry: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * StrandedDrafts
         * @description What one client had and nobody else ever got.
         *
         *     The question drafts exist to answer. A machine that never comes back
         *     cannot report its own, which is why the flag is the server's.
         */
        StrandedDrafts: {
            /** Drafts */
            drafts: components["schemas"]["Stranded"][];
        };
        /**
         * StreamEvent
         * @description DEPARTURE: a create's metadata rides in `value`, as every other event's
         *     payload does. The contract spreads it over the event, where its `type`
         *     ("file"/"folder") is shadowed by the event's own `type` ("create") and the
         *     client can no longer tell a file from a folder.
         *
         *     `transaction` does the job the old `version` field did as well: it is the
         *     id of the transaction this event announces, which IS the new token for the
         *     property it changed. On an event for property P, set the value and set P's
         *     token to `transaction`.
         */
        StreamEvent: {
            type: components["schemas"]["Event"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /** Value */
            value?: components["schemas"]["Metadata"] | components["schemas"]["Moved"] | string | boolean | null;
            /** User */
            user?: string | null;
            at: components["schemas"]["Occurrence"];
        };
        /** TextBody */
        TextBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Content */
            content: string;
        };
        /**
         * Type
         * @enum {string}
         */
        Type: "file" | "folder";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Version
         * @description One thing this file has said, and where that stands.
         */
        Version: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            at: components["schemas"]["Occurrence"];
            standing: components["schemas"]["Standing"];
            kind: components["schemas"]["Kind"];
            /** Size */
            size?: number | null;
            /** Why */
            why?: string | null;
        };
        /**
         * Versions
         * @description One entry, at the transactions a client was looking at.
         *
         *     Every field but `id` is optional so that a caller can ask about as little
         *     as it knows. A client replicating a whole filesystem sends all four; one
         *     asking only what a file held sends `content_version` alone.
         */
        Versions: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name Version */
            name_version?: string | null;
            /** Parent Version */
            parent_version?: string | null;
            /** Deleted Version */
            deleted_version?: string | null;
            /** Content Version */
            content_version?: string | null;
        };
        /** Write */
        Write: {
            /**
             * Transaction
             * Format: uuid
             */
            transaction: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Offset */
            offset?: number | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "write";
            /**
             * Content Version
             * Format: uuid
             */
            content_version: string;
            /** Content */
            content: components["schemas"]["TextBody"] | components["schemas"]["BinaryBody"];
            /**
             * Draft
             * @default false
             */
            draft: boolean;
            /** Predecessor */
            predecessor?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    initialize_wsfs_workspaces__workspace_id__initialize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitializeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InitializeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transact_wsfs_workspaces__workspace_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"] | components["schemas"]["Delete"] | components["schemas"]["Rename"] | components["schemas"]["Reparent"] | components["schemas"]["Move"] | components["schemas"]["Write"] | components["schemas"]["Snapshot"] | components["schemas"]["Execute"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_blob_wsfs_workspaces__workspace_id__blobs__digest__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    store_wsfs_workspaces__workspace_id__blobs__digest__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                digest: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_wsfs_workspaces__workspace_id__entries__entry_id__content_get: {
        parameters: {
            query?: {
                content?: string | null;
            };
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_wsfs_workspaces__workspace_id__entries__entry_id__history_get: {
        parameters: {
            query?: {
                before?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    executions_wsfs_workspaces__workspace_id__entries__entry_id__executions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Executions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_taken_wsfs_workspaces__workspace_id__snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotTaken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stranded_drafts_wsfs_workspaces__workspace_id__drafts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrandedDrafts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_drafts_wsfs_workspaces__workspace_id__drafts_cleared_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Clearing"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconstruction_wsfs_workspaces__workspace_id__reconstruction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconstructionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconstructionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_wsfs_workspaces__workspace_id__stream_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One `data:` line per event, in position order, and a `: hb` comment every heartbeat. Declared here because this payload is what a client's confirmed map is mutated by -- an undeclared one could not be generated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                    "application/json": components["schemas"]["StreamEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ensure_room_wsfs_workspaces__workspace_id__rooms__entry_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomStanding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    warm_room_wsfs_workspaces__workspace_id__rooms__entry_id__warm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    room_stored_wsfs_workspaces__workspace_id__rooms__entry_id__stored_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomStored"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hand_over_wsfs_workspaces__workspace_id__rooms__entry_id__updates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
